# Generated by Django 4.2.2 on 2023-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
    ]
