# Generated by Django 4.2.2 on 2023-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCountry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_id', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
