# Generated by Django 4.2.2 on 2023-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appcountry_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.DateTimeField()),
                ('generation', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='AppCountry',
        ),
    ]
